### ISSUE TITLE
Not found 404 errors returned on served images

### ISSUE THREAD

**Issue by imoutsatsos** [medusa-project/cantaloupe#91] opened 2017-01-20 20:32 UTC
Hi and happy New Year Alex!
I'm trying to troubleshoot some 404 errors for images served from Cantaloupe, and not having a better idea  I'm posting here. Please, let me know if there is a better place for that.

Anyway, I've constructed a page that includes a Seadragon viewer that displays images served from a Cantaloupe server. Having constructed an array of image urls that looks each looking something like this: "http://localhost:8182/iiif/2/%2FJTM_15%2F4_6_4%2Ftest43_Microbeads_on_EnhancedMicrobeads.jpg/info.json" I call the OSD api call, `viewer.open(tileSources)` 

This works most of the time, as shown below
![image](https://cloud.githubusercontent.com/assets/3408226/22163947/0dd68f06-df23-11e6-894b-fe54838ec131.png)

...but there are some images where the AJAX request returns a 404 error (these images are shown black in the viewer).

The following errors appear in the chrome console
![untitled_clipping_012017_031207_pm](https://cloud.githubusercontent.com/assets/3408226/22163894/cff258d2-df22-11e6-9cc9-b3a0cd65f240.jpg)

When I click on these 404 error links I'm able to successfully open the image from the Cantaloupe server. Any ideas why some of the images generate 'Not Found' errors while others work fine? Cantaloupe is setup with a simple FileSystemResolver and all the images are in the same folder The images generating these errors seem are not always the same. Thanks for any feedback.

Best regards
Ioannis

**Comment by adolski** [comment] 2017-01-20 22:18
Hi @imoutsatsos,

A few questions to help me troubleshoot:

1. Are you still on the `develop` branch? Have you pulled lately?

2. Do the same images fail each time, or is it random?

3. Are you using FilesystemCache? If so, does this continue to happen with the cache disabled (`cache.derivative = (empty)`)?

4. Do you see anything interesting in the image server log? For example, when you load up one of those images, there should be a line like:

`INFO  e.i.l.c.r.FilesystemResolver - Resolved image.jpg to /path/to/image.jpg`

Does the image at that path exist and is it readable?

Have a good weekend!

**Comment by imoutsatsos** [comment] 2017-01-20 22:28
Hi, thanks for looking into this!

1.  Yes just build this today from `develop` branch
2.  No, failures are random, different images at different times
3.  I don't hink so. Here is what I see in admin console (so it is happening with cache disabled)
![image](https://cloud.githubusercontent.com/assets/3408226/22167618/8fae6bb8-df35-11e6-8a88-2b26f10e039d.png)
4. Yes, the image at that path exist and is it readable (please, see last paragraph in the issue description)

Have a great weekend too!

**Comment by adolski** [comment] 2017-01-23 20:35
Using ImageMagickProcessor, I loaded 100 images into an OpenSeadragon browser and scrolled through them, and I wasn't able to reproduce this. It smells like a concurrency bug, so I fired off a bunch of simultaneous requests -- also couldn't reproduce.

It's strange that the error is 404. There isn't much that can cause that. With FilesystemResolver & BasicLookupStrategy, I think the only thing is [this](https://github.com/medusa-project/cantaloupe/blob/develop/src/main/java/edu/illinois/library/cantaloupe/resolver/FilesystemResolver.java#L178-L179).

It would help me a lot if you could try the following:

1. Set `print_stack_trace_on_error_pages = true` in Cantaloupe config
2. In Firefox's Web Developer, open the Network tab
3. Reload the page and get a 404 to happen
4. Click on one of the 404 requests in the Network tab
5. Click on the Response tab to the right. This should contain HTML source code, which should contain a stack trace.

Also, any relevant `WARN`s or `ERROR`s in the log would be helpful too.

**Comment by devanonyme** [comment] 2017-05-24 13:44
I'm currently working on getting more information on a issue that was improved from other fixes last year but there it does look like there is some little problems left. Once in a while, when we are loading multiple images at the same times, one or multiple images can fail to load.

Last investigation in december suggested a issue between cantaloupe and client (proxy or network) but there was not progress after that.

I did a setup yesterday that helps reproduce the issue more often that looks like the one I had last year.

The setup:
Page that display OpenSeadragon instance at the same times as multiple images in another panel (browser and cantaloupe cache deactivated), I sometimes get 404 and 500 errors (the stack trace vary, I had some that looked like coming from ruby script). (which seem to be different from the errors we had last year(?))

As my main goal was to isolate the issue I created a basic html page with multiples images (i used the same as the "setup" , 20 images at around 2000x2000  source size) and used a local basic Cantaloupe instance. I was to able to reproduce the 500 errors but not the 404 so far.

I tried to put some breakpoints in toStatus but they doesnt seem to be hit, maybe a misconfiguration of the debugger in regard to multiple threads? Also, I dont see the stack traces... maybe it's not possible when running using standalonEntry.java?

**Comment by devanonyme** [comment] 2017-05-24 14:13
I was able to figure out my problem with breakpoints, I had to set the properties to suspend all threads. When I was breaking, the threads where completing in the background, maybe I will be able to catch the 500 now.

**Comment by adolski** [comment] 2017-05-26 17:36
Still haven't been able to reproduce the 404s, but I did find some 500s, and created a separate issue for those: #114

**Comment by adolski** [comment] 2017-06-01 17:33
Also I found and fixed another bug (#116) that could have been affecting OpenSeadragon, but it didn't involve 404s or 500s.

**Comment by devanonyme** [comment] 2017-06-12 13:43
Hello,

I was in vacation last week, I will surely be able to test the fix you did on #114. My guess was that the 404 errors where another symptom of the same problem but very likely only occury with reverse proxy (wich we use in other env but I dont have reproduced in my local setup (to remove a variable)).

**Comment by adolski** [comment] 2018-08-24 20:00
I'm going to close this because I've never been able to reproduce it and it's several versions behind now. Feel free to reopen if you are still encountering it.

**Closed by adolski** 2018-08-24 20:00 UTC
