### ISSUE TITLE
Frequent HEAD requests to source with filesystem cache and resolve_first = false

### ISSUE THREAD

**Issue by qadan** [medusa-project/cantaloupe#179] opened 2017-11-29 16:42 UTC
This may be a misunderstanding on my part of how the resolve_first functionality works?

We have a server that is configured with the following components:

* Cantaloupe is running as a servlet in Tomcat 7.0
* JP2s are being sourced from Apache locally on the same system
* The webserver itself is running on Apache and is using Openseadragon to display tiles; Openseadragon is requesting IIIF2 data from Cantaloupe through a ReverseProxy configured in Apache
* Cantaloupe is configured to serve these JP2s using:
  * The `HTTPResolver` to convert requests to Cantaloupe into requests to Apache using the delegates script. This includes identifying information about the location of the JP2 as far as the webserver is concerned, as well as a limited-use authentication token Cantaloupe can use to initially request the JP2 and place it in the cache
  * The `OpenJpegProcessor` to process the obtained JP2s
  *  `StreamProcessor.retrieval_strategy` set to `CacheStrategy` to make that all work
  * `cache.source` set to `FilesystemCache` in order to make _that_ work
  * `cache.server.resolve_first` set to `false`

The intent here is to have Cantaloupe initially source the image from the webserver, making its initial authenticated HEAD and GET request, cache the obtained image, and then have tiles served using the cached copy so that we can expire the auth token after two uses. However, we're seeing tons of the following coming in to Apache's access logs when tiles are being requested:

```
127.0.0.1 - - [29/Nov/2017:11:12:24 -0400] "HEAD /path/to/jp2?token=authenticatedtoken HTTP/1.1" 200 401 "-" "Restlet-Framework/2.3.11"
```

If we expire the token after only two uses, Cantaloupe keeps making more of these requests and 403s subsequently since it's no longer authorized, then tosses a 500 back to Openseadragon

Obviously there are a ton of ways we can authenticate Cantaloupe differently to mitigate the issue; this is just a bandaid over our existing Djatoka methodology to get it working. We're more concerned about the frequent HEAD requests, the assumption was that once the JP2 was cached and Cantaloupe was being told not to `resolve_first`, that no further HEAD requests to the source would be required since the cache contains everything needed? Are we just missing something in the config? I'll stick a link to a gist with our configs in here:

https://gist.github.com/qadan/1395a21dcee7861d89436ba55bb5ee74

**Comment by adolski** [comment] 2017-11-29 23:28
Hi @qadan,

There are a couple of issues here: one is that HttpResolver in 3.3.x makes more requests than it should have to. The other is that the Image API v1 and v2 request handlers in 3.3.x aren't dealing with `cache.server.resolve_first` correctly -- it broke at some point and there is no test for it in 3.3.x.

Both of the above have been fixed in 3.4-SNAPSHOT (`develop` branch) (with tests), but I never got around to fixing 3.3.x and I don't know if I will. (Time constraints and these two branches have diverged greatly.)

If you are able to build your own 3.4 snapshot, that ought to solve this; otherwise, I'm hoping to release 3.4 before long, maybe in a month or two. Sorry for the inconvenience.

**Comment by qadan** [comment] 2017-11-30 21:05
Hi, thanks for the quick response!

I've built a .war from the `develop` branch and monitored the Apache access logs and it does indeed cut the number of requests down to a dual HEAD/GET instead of many per-tile-request HEADs, which resolves the issue. We'll have to run off of the `develop` branch for the time being, it sounds like. Thanks for the assistance!

**Comment by adolski** [comment] 2017-11-30 22:05
Excellent!

**Closed** 2017-11-30 22:05 UTC
Labels: bug

**Comment by qadan** [comment] 2018-01-15 14:55
Hi there! Since the 3.4 release, we've made an attempt to move from the SNAPSHOT .war we had compiled over to the 3.4 release branch and ended up having this same issue again - not precisely as it was before, but the same core issue.

On 3.4-SNAPSHOT, we were getting:
* One HEAD request
* One GET request

On 3.4 release, we're seeing:
* One HEAD request
* One GET request
* Another subsequent HEAD request
* One additional HEAD request every time a tile is requested - no additional GET requests are being made, so it does seem like tiles are being served from the cache, but it's still making HEAD requests first

We haven't changed any of our configs between SNAPSHOT and release; is there something we're missing or could there be a resurgence of the issue?

**Comment by adolski** [comment] 2018-01-15 17:00
Hi @qadan,

I see the expected HEAD+GET duo in the 3.4 release, but I can't reproduce the subsequent HEAD request.

It's strange that there would be one, given how HttpResolver caches the HEAD response, and even stranger that it would be occurring *after* the GET...

The additional HEAD requests (one per tile a.k.a. request) would be normal if `cache.server.resolve_first` were `true`, abnormal otherwise, but it's working correctly for me.

Also added a test for this, just to be sure, which is passing.

Not sure where to go from here. Is it possible that there are multiple requests, for the same resource perhaps, getting conflated in your web server logs?

**Comment by qadan** [comment] 2018-01-30 13:00
Sorry for the delay, I wanted to run some tests of my own locally to be sure of what was happening.

It looks like, in the case of specifically the resource I was attempting this with, the server the image was originating from was serving up uncacheable HEAD requests for unauthenticated users, so it'd appear that cantaloupe's behaviour is as expected. We're going to modify behaviours on our end to make sure the HEAD requests can be appropriately cached.

**Comment by qadan** [comment] 2018-02-09 13:31
Digging into this a little bit more, actually ... looks like the specific case where we're getting repeated HEAD requests is across multiple independent requests from the source through the `HttpResolver` when using the `FilesystemCache`. Order seems to be:

* `ImageResource` does a `doGet()`, which generates a new `HttpResolver`
* `HttpResolver` runs `setIdentifier()`, setting the cached `headResponse` to `null`
* `doGet()` runs `checkAccess()` on the resolver, which generates a `HEAD` request
* Subsequent requests for the resource generate new instances, which run through the same process of generating a new `HttpResolver` with a new `headResponse` set to `null`
* The next run through `checkAccess()` spawns a new `HEAD` request

Wondering if this is the intended behaviour I guess? The comment on `headResponse` describes it as being cached, but that could be intended just in a single session?

The following test should show this in action:

https://gist.github.com/qadan/7ce2e3d929c1962376043ac311185801

**Comment by adolski** [comment] 2018-02-09 14:56
This sounds normal to me. There is one resolver per request, and they aren't reused or shared across requests/threads. `headResponse` is cached in an instance variable, so calling `checkAccess()` multiple times on the same instance will prevent multiple `HEAD` requests from that instance; but, if there are 30 instances in different threads that each need to make the same request, then indeed there will be 30 `HEAD` requests.

**Comment by qadan** [comment] 2018-02-12 18:31
Okay, thanks again for the response! Just checking that this is the intended behaviour.

**Comment by qadan** [comment] 2018-02-12 19:30
Given that our organization's use case necessitates being able to make limited requests to the source (given an authorization token that expires after n uses), but the current code necessitates being able to make an unknown number of HEAD requests across several sessions, would you be open to a pull request that makes it possible to cache HEAD requests for items in the source cache for a single identifier across multiple sessions? Say, placed behind a config option that's false by default, e.g., `cache.server.source.cache_head_between_sessions` (not a great name), and that respects `cache.server.source.ttl_seconds` as the amount of time it hangs on to these responses for?

**Comment by adolski** [comment] 2018-02-14 16:36
I see what you mean. I think some improvements are possible here. I'll open a new issue for this.
