### ISSUE TITLE
Refreshing the image cache when normalization changes

### ISSUE THREAD

**Issue by imoutsatsos** [medusa-project/cantaloupe#115] opened 2017-06-01 14:52 UTC
Hi Alex; 
First I would like to say that I have introduced Cantaloupe in our digital microscope image review workflow with excellent results. Response using the ImageMagick processor is good even with image collections of several hundred images. Thank you for continuing the development of this really easy to use and agile server!

Now, I'm trying to address a requirement where the images must be presented to users without intensity normalization (see previous issue #49 ). I'm finding that this works for newly retrieved images but the cache is not refreshed, so images viewed previously still appear intensity normalized. I've restarted the server thinking that this would clear and refresh the cache but I did not see any difference.

How do I go about clearing the cache so that the new normalization settings take effect?
Also, can you think of what would be the best approach for setting custom intensity settings for a particular session? The 'Normalize' setting is global to the server, and some users may or may not want to use it. So manipulating some of these settings in the API would be preferred. I'm wondering whether these options could be added to the IIIF API or can be implemented otherwise. Are you attending the IIIF Vatican meeting?

Thanks and best regards
Ioannis

**Comment by adolski** [comment] 2017-06-02 19:18
Hi Ioannis,

Thanks for reporting this. The intended behavior is for `processor.normalize = true` images to be cached separately from `processor.normalize = false` images, but I see that they are not, in 3.3. I've just pushed a fix and it will appear in 3.3.1 (which I'm hoping to release soon).

As for being able to control normalization on the client side -- I will comment on that soon. Have a good weekend!

**Comment by imoutsatsos** [comment] 2017-06-02 20:21
Excellent. Thank you, you too!

**Comment by adolski** [comment] 2017-06-05 18:21
Hi again, here are my thoughts on client-side normalization:

It's not possible to do this on the client using pure IIIF Image API. The spec doesn't forbid augmentation with extra functionality, and a couple of the processors do this already -- PdfBoxProcessor accepts a `?page=` query argument, for example -- but that's a hack with big limitations and I wish it wasn't needed.

I can't think of a good solution for this. I do think it would be useful to bring this up with the IIIF people -- the need for more operations and/or a way to extend the API to allow for custom operations.

If they don't want to tackle this, then some other API would be needed, I think. I know that IIP offers contrast adjustments, but I don't know about auto-stretching. (And, it's 20 years old.) Other than that, I'm not familiar at all with what's available outside of libraries. Is there anything like the Image API in some other field?

**Comment by imoutsatsos** [comment] 2017-06-06 22:40
Thank you for sharing your thoughts on this. I also discussed it with several people at the IIIF meeting that I'm attending. I think there is general agreement that advanced image filtering/processing must happen on the client side. Mirador for example seems to have a full set of controls for adjusting the image. I need to explore more to understand if it will help with my specific problem.

Finally, I and several other participants from the Stanford IIIF delegation agreed that Cantaloupe is one of the easiest IIIF image servers to setup and quite performant indeed!
Apparently, Stanford is using Cantaloupe for most of their hands-on workshops when they want to setup a IIIF server without too much fuss.

I much appreciate your development of Cantaloupe and love to talk about it!

Best regards
Ioannis

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by adolski** [comment] 2017-06-08 19:54
Awesome, thanks for the heads-up, and good to know that people are finding Cantaloupe useful.

I haven't looked much at Mirador, but it would be interesting to find out how it accomplishes this.

**Comment by adolski** [comment] 2017-06-08 20:04
I'm going to close this as a fixed bug and pick up the discussion in #117.

**Closed by adolski** 2017-06-08 20:04 UTC
Labels: bug

**Comment by imoutsatsos** [comment] 2017-08-23 20:48
I have created a demo with client side javascript image processing using the OpenSeadragon viewer and its plugin to work out some the pros/cons of this approach. With progress in #142 I'm hopeful that we will be able to address most of the use cases. Here is the demo: https://imoutsatsos.github.io/osdUseCaseHCS/  and its associated gitHub project https://github.com/imoutsatsos/osdUseCaseHCS
